### PR TITLE
Neaten up constants and move getting settings from env out of the main widget.

### PR DESCRIPTION
**Pull request by samcunliffe**
Solves
- #133 

which is nice from a maintainability point of view.

### CODE REVIEW

**Review by palvarezc — CHANGES_REQUESTED** [review]
Too other layers have proper names, could we add them too? 

They would need to live in `_main_widget.py` I guess:

```python
MEASUREMENTS_LAYER_NAME = "Radii and Lengths"
IMAGE_LAYER_NAME = "Particle Tracks"
```

**Comment by samcunliffe** [comment]
> Too other layers have proper names, could we add them too?
> 
> They would need to live in `_main_widget.py` I guess:
> 
> ```python
> MEASUREMENTS_LAYER_NAME = "Radii and Lengths"
> IMAGE_LAYER_NAME = "Particle Tracks"
> ```

Oops! I missed them.

**Review by palvarezc — APPROVED** [review]
Love this!

**Comment by samcunliffe** [comment]
Also solves #56

**Pull request merged**
