### PR TITLE
Revert "Button hiding logic and new UI for bottom docking"

### PR DESCRIPTION
**Pull request by Joseph-Garvey**
Reverts palvarezc/cavendish-particle-tracks#131 due to issue where pop up windows do not display.

### CODE REVIEW

**Comment by palvarezc** [comment]
@Joseph-Garvey , can you explain a bit more what the problem is. I just pulled main and everything seems ok.

**Comment by Joseph-Garvey** [comment]
Maybe the issue is only on windows? I click the magnification, stereoshift or decay angles button and no pop up window appears.

**Comment by palvarezc** [comment]
> Maybe the issue is only on windows? I click the magnification, stereoshift or decay angles button and no pop up window appears.

Weird, working for me on macOS... let's see if @samcunliffe can reproduce?

**Comment by Joseph-Garvey** [comment]
in main:

https://github.com/user-attachments/assets/9ad250ce-a462-4ae5-a431-72862fcf747f

**Comment by Joseph-Garvey** [comment]
and in ```button_logic```

https://github.com/user-attachments/assets/5ad1f08d-cd98-4733-87b3-fb51cb6239e2

**Comment by samcunliffe** [comment]
> > Maybe the issue is only on windows? I click the magnification, stereoshift or decay angles button and no pop up window appears.
> 
> Weird, working for me on macOS... let's see if @samcunliffe can reproduce?

I don't have any data other than the two example tiffs in `tests/data`. So I can no longer test anything in landscape mode.

The ascii art looks quite bad though...

Screenshot 2024-09-24 at 11 21 50

**Comment by samcunliffe** [comment]
... probably the right thing to do here is add a test. We will presumably see it fail on Windows but not others?

**Comment by palvarezc** [comment]
I just checked in Windows in the lab machine and I don't see the same issue.... Dialogs seem to open fine.

**Comment by palvarezc** [comment]
Created some test data, but found a problem on loading:

```
 UnknownFormatError: Could not detect your file type because it did not have an extension. Try specifying a loader class, e.g. Video(C:/Users/pa459/Documents/data\VIEW1\/*)
```

which is strange as this is what the tests do, and the tests pass in this machine. Something going on between `\` and `/`? But for @Joseph-Garvey this has been working on Windows all along.... I am a bit puzzled.

**Comment by Joseph-Garvey** [comment]
@samcunliffe 
> I don't have any data other than the two example tiffs in `tests/data`. So I can no longer test anything in landscape mode.

If you look at PR #112 there's a file called testdims. It generates fake data to make development easier, worth using it on your instance maybe?

**Comment by Joseph-Garvey** [comment]
> Created some test data, but found a different problem on loading:
> 
> ```
>  UnknownFormatError: Could not detect your file type because it did not have an extension. Try specifying a loader class, e.g. Video(C:/Users/pa459/Documents/data\VIEW1\/*)
> ```
> 
> which is strange as this is what the tests do, and the tests pass in this machine. Something going on between `\` and `/`? But for @Joseph-Garvey this has been working on Windows all along.... I am a bit puzzled.

I have no issues using the real data or fake data generated by ```testdims.py```. Although testdims isn't using the load data functions, it's just creating layers that have 4 dimensions to get past the intro screen.

**Comment by palvarezc** [comment]
> ... probably the right thing to do here is add a test. We will presumably see it fail on Windows but not others?

I think probably our tests already would fail if the dialogs would not show, but added a new one just in case:
- #150

**Comment by palvarezc** [comment]
> Have tried wiping and reinstalling the plugin. It doesn't seem to help. Are you all using napari 0.5.2?

I am in `0.5.3`

**Comment by Joseph-Garvey** [comment]
Updating to napari 0.5.3 does not resolve the issue.

**Comment by Joseph-Garvey** [comment]
Tests pass, except for test_version_fallback...

**Comment by Joseph-Garvey** [comment]
Looks identical to the config from the lab pcs.

**Review by samcunliffe — CHANGES_REQUESTED** [review]
Needs some work to check that this is a reproducible issue.

**Comment by samcunliffe** [comment]
@palvarezc you've tested on the lab computers, right? So I think we can close here.

(We can always reopen)

**Pull request closed without merging**
