### PR TITLE
Merging stereoshift changes from dev_ux into main

### PR DESCRIPTION
**Pull request by Joseph-Garvey**
This update will allow the user to take many measurements of stereoshift, with arrows pointing between different viewpoints.

### CODE REVIEW

**Comment by Joseph-Garvey** [comment]
- [ ] Fix tests

**Comment by palvarezc** [comment]
I think the easiest way to implement what we need would be to duplicate the stereoshift attributes for each `NewParticle` object, to have one measurement for `_origin_vertex` and one for `_decay_vertex`. Then the `StereoshiftDialog` will request the user to select whether the measurement to be performed is associated to the origin or decay vertex, and save the stereoshift information to the corresponding attribute in the table and data dictionary.

**Comment by Joseph-Garvey** [comment]
- [ ] Clarify what we want displayed to the user.

**Comment by Joseph-Garvey** [comment]
Ready for review, suffers from the same issue caused by the premature merge I did earlier today.
Can rectify in main then remerge here.

**Comment by Joseph-Garvey** [comment]
Only thing left is to update the UI tests to the new UI

**Review by samcunliffe — CHANGES_REQUESTED** [review]
With these modifications something in the stereoshift dialog setup is adding a huge number of image slices.

The new "event" and "view" toolbar (which is a nice idea!) seems swapped... I have two sets of three fake images (two events).

Screenshot 2024-09-25 at 21 20 30

We should have some tests to cover this. Possibly going TDD for this feature, since it seems its easy to give a wrong dimension somewhere and create a comedy array of events.

Also tests fail.

**Pull request closed without merging**
